train: False

gpu_number: '0'

training_img_root: ''
validation_img_root: ''

training_img_names: ['']
validation_img_names: []

# Training settings
resume: False
save_weights: False
save_weights_path: ''
save_training_stats: False

# Training hyperparameters
learning_rate: 0.0001
epochs: 8192
batch_size: 128
model_weights_path: ''
training_patch_size_20: 32
training_patch_size_60: 96

beta_1: 0.9
beta_2: 0.999
epsilon: 0.00000001
schedule_decay: 0.004


number_bands_10: 4
number_bands_20: 6
number_bands_60: 2

# Test settings
border_20: 8
border_60: 12

test_patch_size_20: 128
test_patch_size_60: 192

original_test: True