train: False
validation: False

gpu_number: '0'

training_img_root: ''


number_bands_10: 4
number_bands_20: 6
number_bands_60: 2

# Training settings

resume: False
save_weights: True
save_weights_path: 'weights'
save_training_stats: False

# Training hyperparameters

learning_rate: 0.0001
epochs: 500
batch_size: 64
model_weights_path: ''
training_patch_size_20: 64
training_patch_size_10: 64

# Target-Adaptive settings

ta_save_weights: False
ta_save_weights_path: ''
ta_save_training_stats: False

# Target-Adaptive hyperparameters

lambda_1: 1.0
lambda_2: 0.01

ta_epochs: 100
# ta_epochs: 50
ta_learning_rate: 0.0001
