train: False

gpu_number: '0'

training_img_root: ''
validation_img_root: ''

training_img_names: ['']
validation_img_names: []

# Training settings
resume: False
save_weights: False
save_weights_path: ''
save_training_stats: False

# Training hyperparameters
learning_rate: 0.002
beta_1: 0.9
beta_2: 0.999
epochs: 200
batch_size: 128
model_weights_path: ''
training_patch_size_20: 33

lambda_1: 1.0
lambda_2: 0.1
lambda_3: 0.01


number_bands_10: 4
number_bands_20: 6




